pretrained_config:
  pretrained_model_name_or_path: 'togethercomputer/LLaMA-2-7B-32K'
  cache_dir: './data/neo/hub' #'/juice/scr/scr110/scr/nlp/data/neo/hub/'
  return_dict: true
  quantization: false
  device_map: auto
  low_cpu_mem_usage: true
  torch_dtype: bfloat16
  rope_theta: 10000.0
  attn_implementation: flash_attention_2